version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "ControlzEx"
        versions: ["5.x", "6.x"]
      - dependency-name: "MahApps.Metro"
        versions: ["3.x"]