version: 1.0.{build}
image: Visual Studio 2019
configuration:
- Release
install:
- cmd: git submodule -q update --init
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- nuget restore
skip_commits:
  files:
    - assets/*
    - '**/*.md'
build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
artifacts:
- path: 'bin**\*.exe'
test: off
deploy:
  release: v$(APPVEYOR_BUILD_VERSION)
  description: 'The Legacinator'
  provider: GitHub
  auth_token:
    secure: GvOeZH3msooHWqoQj46UsLaojyMsnudmNdfEMUSJJfrIBuLwAYaMeI5FcxKSFVv7
  artifact: /.*\.exe/
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true