version: 1.2.{build}
image: Visual Studio 2022
configuration:
  - Release
install:
  - cmd: git submodule -q update --init
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - nuget restore
skip_commits:
  files:
    - assets/*
    - '**/*.md'
build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
artifacts:
  - path: 'bin**\*.exe'
test: off
deploy:
  - provider: Environment
    name: GITHUB
    on:
      branch: master
      APPVEYOR_REPO_TAG: true